[httpRequest]
timeout_second = 5                              # 爬虫的超时时间

[params]
timezone = 'Asia/Shanghai'                      # 时区

[db]
db_path = "data/earthquake.db"                  # SQLite数据库位置

[redis]
enable = false                                  # 是否连接Redis，项目没有解耦模块，默认不连接，如有需要请自行扩展
addr = "localhost"                              # redis地址
port = 6379                                     # redis端口
password = ""                                   # redis密码
db = 0                                          # 保持默认值就行

[jpquake]
enable = true                                   # 是否开启日本地震信息爬虫
crawl_interval = 60                             # 爬虫间隔（秒）
parse_after_minute = 3                          # 获取到的地震情报距离几分钟后进行解析，因为有些地震刚记录时没有任何信息，因此等一段时间信息完善后再加入

[jpeew]
enable = true                                   # 是否开启日本EEW爬虫
crawl_interval = 1                              # 爬虫间隔（秒）
redis_enable = false                            # 是否向redis推送
redis_key = "jpeew"                             # 如推送，使用的键名

[email]                                         # 以下参数建议看邮件服务商官方文档填写
enable = true                                   # 邮件推送总开关
host = ""                                       # SMTP服务器地址
port = 465                                      # SMTP服务器端口
username = ""                                   # 用户名（一般就是邮箱地址）
password = ""                                   # 密码（有的是账户密码，有的是token，看文档）
alias = "quakebot"                              # 邮件发送者的alias
max_retries = 3                                 # 一封邮件最多尝试重发几次
[email.receive]
receiver_users = []                             # 接收邮件的账户，如有多个按字符串数组形式写入
[email.receive.jpquake]
receive = false                                 # 是否推送日本地震信息
max_receive_once = 3                            # 当一次解析到超过几条日本地震信息时不发送邮件，以免大量邮件一次性涌入，设置为小于等于0的数关闭此功能
[email.receive.jpeew]
receive = true                                  # 是否通过邮件推送日本EEW信息
receive_alert_only = false                      # 只推送紧急地震速报（警报）吗？（即预想最大震度>=5-的地震速报）
receive_train = true                            # 推送训练用EEW吗？

[telegram]                                      # TG机器人推送设置，同样建议参考官方文档
enable = true                                   # telegram机器人推送总开关
bot_token = ""                                  # 生成的bot token
max_retries = 3                                 # 最大尝试次数
max_send_once_a_time = 3                        # 最大限制并发发送信息数
max_receive_once = 3                            # 同上(邮件部分)
[telegram.receive]
receive_users = []                              # 接收推送的用户telegram id（整数格式， int64)
[telegram.receive.jpquake]
receive = true                                  # 同邮件
max_receive_once = 3                            # 同邮件
[telegram.receive.jpeew]
receive = true                                  # 同邮件
receive_alert_only = false                      # 同邮件
receive_train = true                            # 同邮件
